variables:
- name:  Build.Repository.Clean
  value: true

trigger:
- release/2.0.0

pr:
- release/2.0.0

jobs:
- job: OSX
  displayName: OSX
  pool:
    vmImage: macOS-10.13
  steps:
  - script: ./build.sh -c

- job: Ubuntu1604
  displayName: Ubuntu16.04
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: ./build.sh -c

- job: Windows_NT
  displayName: Windows_NT
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: build.cmd -c
